# Generated by Django 6.0.5 on 2026-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('LIBRARIAN', 'LIBRARIAN')], max_length=20),
        ),
    ]
