# Generated by Django 6.0.5 on 2026-05-07 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_author_genre_alter_user_managers_book_borrowrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='LMS.book'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
